export type ASSDCodes = {
    account: Record<string, string>;
    billit: Record<string, string>;
    boardd: Record<string, string>;
    boardslot: Record<string, string>;
    boardstart: string[];
    boardtype: Record<string, string>;
    bookroom: Record<string, string>;
    floor: string[];
    guestcode: Record<string, string>;
    guestp: Record<string, string>;
    guestpr: Record<string, string>;
    hierarchy: Record<string, string>;
    jstate: Record<string, string>;
    jsubtype: Record<string, string>;
    jtype: Record<string, string>;
    language: Record<string, string>;
    matchdef: Record<string, string>;
    nation1: Record<string, string>;
    nation2: Record<string, string>;
    nation3: Record<string, string>;
    pricetype: Record<string, string>;
    regcode: Record<string, string>;
    salut1: Record<string, string>;
    salutation: Record<string, string>;
    st_agreem: Record<string, string>;
    st_conf: Record<string, string>;
    st_incl: Record<string, string>;
    st_lett_cr: Record<string, string>;
    st_lett_cu: Record<string, string>;
    st_payment: Record<string, string>;
    st_rbbed: Record<string, string>;
    st_rbrtype: Record<string, string>;
    transact: Record<string, string>;
    type2: Record<string, string>;
    type3: Record<string, string>;
    type4: Record<string, string>;
    type5: Record<string, string>;
    type6: Record<string, string>;
    weekday: string[];
};